package com.susar.service;

import com.susar.model.specialist.Specialist;

import java.util.List;

public interface SpecialistService {

    Specialist create(Specialist specialist);                 //return autogenerated specialistId

    void update(Long specialistId, Specialist specialist);

    void delete(Long specialistId);

    Iterable<Specialist> getAllSpecialists();

    List<String> getStudies();

    List<String> getCountries();
}
