package com.susar.service;

import com.susar.model.Susar;
import java.util.List;

public interface SusarService {

    Susar create(Susar susar);                 //return autogenerated susarId

    Susar read(Long susarId);

    void update(Long susarId, Susar susar);

    void delete(Long susarId);

    Iterable<Susar> getAllSusars();

    List<Susar> filterByType(List<String> types);

    List<String> getTypes();

    List<String> getStudies();

    List<String> getCountries();

    List<String> getSites();


}
